// Mocks generated by Mockito 5.4.6 from annotations
// in app_restaurante/test/ui/viewmodels/dish_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:app_restaurante/data/model/dish.dart' as _i4;
import 'package:app_restaurante/data/services/firestore/dish_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DishService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDishService extends _i1.Mock implements _i2.DishService {
  MockDishService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.Dish>> watchDishes() =>
      (super.noSuchMethod(
            Invocation.method(#watchDishes, []),
            returnValue: _i3.Stream<List<_i4.Dish>>.empty(),
          )
          as _i3.Stream<List<_i4.Dish>>);

  @override
  _i3.Future<List<_i4.Dish>> getAllDishes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllDishes, []),
            returnValue: _i3.Future<List<_i4.Dish>>.value(<_i4.Dish>[]),
          )
          as _i3.Future<List<_i4.Dish>>);

  @override
  _i3.Future<_i4.Dish?> getDishById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getDishById, [id]),
            returnValue: _i3.Future<_i4.Dish?>.value(),
          )
          as _i3.Future<_i4.Dish?>);

  @override
  _i3.Future<void> createDish(_i4.Dish? dish) =>
      (super.noSuchMethod(
            Invocation.method(#createDish, [dish]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateDish(_i4.Dish? dish) =>
      (super.noSuchMethod(
            Invocation.method(#updateDish, [dish]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteDish(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDish, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
