// Mocks generated by Mockito 5.4.6 from annotations
// in app_restaurante/test/ui/viewmodels/reservation_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:app_restaurante/data/model/reservation.dart' as _i4;
import 'package:app_restaurante/data/services/firestore/reservation_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ReservationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockReservationService extends _i1.Mock
    implements _i2.ReservationService {
  MockReservationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.Reservation>> watchAll() =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, []),
            returnValue: _i3.Stream<List<_i4.Reservation>>.empty(),
          )
          as _i3.Stream<List<_i4.Reservation>>);

  @override
  _i3.Stream<List<_i4.Reservation>> watchByUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchByUser, [userId]),
            returnValue: _i3.Stream<List<_i4.Reservation>>.empty(),
          )
          as _i3.Stream<List<_i4.Reservation>>);

  @override
  _i3.Future<void> createReservation(_i4.Reservation? r) =>
      (super.noSuchMethod(
            Invocation.method(#createReservation, [r]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateReservation(_i4.Reservation? r) =>
      (super.noSuchMethod(
            Invocation.method(#updateReservation, [r]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteReservation(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteReservation, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateStatuses(List<String>? ids, String? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateStatuses, [ids, status]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.Reservation?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i3.Future<_i4.Reservation?>.value(),
          )
          as _i3.Future<_i4.Reservation?>);

  @override
  _i3.Future<List<_i4.Reservation>> getActiveByUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveByUser, [userId]),
            returnValue: _i3.Future<List<_i4.Reservation>>.value(
              <_i4.Reservation>[],
            ),
          )
          as _i3.Future<List<_i4.Reservation>>);
}
