// Mocks generated by Mockito 5.4.6 from annotations
// in app_restaurante/test/ui/viewmodels/user_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i10;

import 'package:app_restaurante/data/model/reservation.dart' as _i8;
import 'package:app_restaurante/data/model/user.dart' as _i4;
import 'package:app_restaurante/data/repositories/reservation_repository.dart'
    as _i7;
import 'package:app_restaurante/data/repositories/user_repository.dart' as _i6;
import 'package:app_restaurante/data/services/firestore/user_service.dart'
    as _i2;
import 'package:app_restaurante/data/services/storage/storage_service.dart'
    as _i9;
import 'package:firebase_auth/firebase_auth.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i2.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.User?> watchUser(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#watchUser, [uid]),
            returnValue: _i3.Stream<_i4.User?>.empty(),
          )
          as _i3.Stream<_i4.User?>);

  @override
  _i3.Future<_i4.User?> getUserById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [id]),
            returnValue: _i3.Future<_i4.User?>.value(),
          )
          as _i3.Future<_i4.User?>);

  @override
  _i3.Future<void> updateUser(_i4.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> ensureUserExistsFromAuth(_i5.User? firebaseUser) =>
      (super.noSuchMethod(
            Invocation.method(#ensureUserExistsFromAuth, [firebaseUser]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i6.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.User?> watchById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchById, [id]),
            returnValue: _i3.Stream<_i4.User?>.empty(),
          )
          as _i3.Stream<_i4.User?>);

  @override
  _i3.Future<void> create(_i4.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#create, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.User?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i3.Future<_i4.User?>.value(),
          )
          as _i3.Future<_i4.User?>);

  @override
  _i3.Future<void> update(_i4.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#update, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> anonymize(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#anonymize, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [ReservationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReservationRepository extends _i1.Mock
    implements _i7.ReservationRepository {
  MockReservationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> create(_i8.Reservation? r) =>
      (super.noSuchMethod(
            Invocation.method(#create, [r]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i8.Reservation>> watchAll() =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, []),
            returnValue: _i3.Stream<List<_i8.Reservation>>.empty(),
          )
          as _i3.Stream<List<_i8.Reservation>>);

  @override
  _i3.Stream<List<_i8.Reservation>> watchByUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchByUser, [userId]),
            returnValue: _i3.Stream<List<_i8.Reservation>>.empty(),
          )
          as _i3.Stream<List<_i8.Reservation>>);

  @override
  _i3.Future<_i8.Reservation?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i3.Future<_i8.Reservation?>.value(),
          )
          as _i3.Future<_i8.Reservation?>);

  @override
  _i3.Future<List<_i8.Reservation>> getActiveByUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveByUser, [userId]),
            returnValue: _i3.Future<List<_i8.Reservation>>.value(
              <_i8.Reservation>[],
            ),
          )
          as _i3.Future<List<_i8.Reservation>>);

  @override
  _i3.Future<void> update(_i8.Reservation? r) =>
      (super.noSuchMethod(
            Invocation.method(#update, [r]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateStatuses(List<String>? ids, String? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateStatuses, [ids, status]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i9.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> uploadDishImage(_i10.File? imageFile, String? dishId) =>
      (super.noSuchMethod(
            Invocation.method(#uploadDishImage, [imageFile, dishId]),
            returnValue: _i3.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#uploadDishImage, [imageFile, dishId]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> deleteDishImage(String? dishUrlImage) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDishImage, [dishUrlImage]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> uploadRestaurantImage(
    _i10.File? imageFile,
    String? restaurantId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadRestaurantImage, [
              imageFile,
              restaurantId,
            ]),
            returnValue: _i3.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#uploadRestaurantImage, [
                  imageFile,
                  restaurantId,
                ]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> deleteRestaurantImage(String? restaurantUrlImage) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRestaurantImage, [restaurantUrlImage]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> uploadUserAvatar(_i10.File? imageFile, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#uploadUserAvatar, [imageFile, userId]),
            returnValue: _i3.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#uploadUserAvatar, [imageFile, userId]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> deleteUserAvatar(String? userUrlImage) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserAvatar, [userUrlImage]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
