// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZLsyPcD0PzH8AjzW_gqhtpBMeaThmXG0',
    appId: '1:941200508100:web:a581db444443043f93b591',
    messagingSenderId: '941200508100',
    projectId: 'fir-proyecto-intermodular',
    authDomain: 'fir-proyecto-intermodular.firebaseapp.com',
    storageBucket: 'fir-proyecto-intermodular.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwGuvxxDp9tQFPQD7AGy55dYBnIoOLti4',
    appId: '1:941200508100:android:7cd004a2809b4fc693b591',
    messagingSenderId: '941200508100',
    projectId: 'fir-proyecto-intermodular',
    storageBucket: 'fir-proyecto-intermodular.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBArg1p54tmEW6frskCxUlZLwIw91pYzW8',
    appId: '1:941200508100:ios:55761e07f71ca21593b591',
    messagingSenderId: '941200508100',
    projectId: 'fir-proyecto-intermodular',
    storageBucket: 'fir-proyecto-intermodular.firebasestorage.app',
    iosBundleId: 'com.example.appRestaurante',
    iosClientId:
        '941200508100-sfsfc2eims1me4qep56aq5q6ofi6agqv.apps.googleusercontent.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBArg1p54tmEW6frskCxUlZLwIw91pYzW8',
    appId: '1:941200508100:ios:55761e07f71ca21593b591',
    messagingSenderId: '941200508100',
    projectId: 'fir-proyecto-intermodular',
    authDomain: 'fir-proyecto-intermodular.firebaseapp.com',
    storageBucket: 'fir-proyecto-intermodular.firebasestorage.app',
    iosBundleId: 'com.example.appRestaurante',
    iosClientId:
        '941200508100-sfsfc2eims1me4qep56aq5q6ofi6agqv.apps.googleusercontent.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZLsyPcD0PzH8AjzW_gqhtpBMeaThmXG0',
    appId: '1:941200508100:web:c3486c158d6e3d0e93b591',
    messagingSenderId: '941200508100',
    projectId: 'fir-proyecto-intermodular',
    authDomain: 'fir-proyecto-intermodular.firebaseapp.com',
    storageBucket: 'fir-proyecto-intermodular.firebasestorage.app',
  );
}
